// Activity Tracker - Kotlin Utilities

fun validateInput(input: String): Boolean {
    if (input.isBlank()) return false
    val regex = Regex("^[a-zA-Z0-9_]+$")
    return regex.matches(input)
}

fun formatDate(timestamp: Long): String {
    val sdf = java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss")
    return sdf.format(java.util.Date(timestamp))
}

fun calculateAverage(numbers: List<Double>): Double {
    if (numbers.isEmpty()) return 0.0
    return numbers.sum() / numbers.size
}

fun reverseString(input: String): String {
    return input.reversed()
}

fun isPrime(n: Int): Boolean {
    if (n < 2) return false
    for (i in 2..Math.sqrt(n.toDouble()).toInt()) {
        if (n % i == 0) return false
    }
    return true
}

fun clamp(value: Int, min: Int, max: Int): Int {
    return maxOf(min, minOf(max, value))
}

fun countWords(text: String): Int {
    if (text.isBlank()) return 0
    return text.trim().split(Regex("\s+")).size
}

fun toTitleCase(str: String): String {
    return str.split(" ").joinToString(" ") { it.capitalize() }
}

fun fibonacci(n: Int): Long {
    if (n <= 1) return n.toLong()
    var a = 0L; var b = 1L
    repeat(n - 1) { val temp = a + b; a = b; b = temp }
    return b
}

fun retry(times: Int, block: () -> Unit) {
    repeat(times) {
        try { block(); return } catch (e: Exception) { }
    }
}

fun bytesToHex(bytes: ByteArray): String {
    return bytes.joinToString("") { "%02x".format(it) }
}

fun splitChunks(list: List<Int>, size: Int): List<List<Int>> {
    return list.chunked(size)
}

fun mapToQueryString(params: Map<String, String>): String {
    return params.entries.joinToString("&") { "=" }
}

fun readableFileSize(size: Long): String {
    val kb = size / 1024.0
    val mb = kb / 1024.0
    return if (mb >= 1) "%.2f MB".format(mb) else "%.2f KB".format(kb)
}

fun getEnvOrDefault(key: String, default: String): String {
    return System.getenv(key) ?: default
}

fun isValidEmail(email: String): Boolean {
    val regex = Regex("^[\\w.-]+@[\\w.-]+\\.[a-zA-Z]{2,6}$")
    return regex.matches(email)
}

fun truncate(text: String, maxLen: Int): String {
    return if (text.length <= maxLen) text else text.take(maxLen) + "..."
}

fun randomString(length: Int): String {
    val chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"
    return (1..length).map { chars.random() }.joinToString("")
}

fun median(numbers: List<Double>): Double {
    val sorted = numbers.sorted()
    val mid = sorted.size / 2
    return if (sorted.size % 2 == 0) (sorted[mid - 1] + sorted[mid]) / 2 else sorted[mid]
}

fun groupByFirstChar(words: List<String>): Map<Char, List<String>> {
    return words.groupBy { it.first() }
}


// Auto commit batch 1779007267
fun autoGenerated_1779007267_line1() { println("Line 1 at 2026-05-17 11:41:06") }
fun autoGenerated_1779007267_line2() { println("Line 2 at 2026-05-17 11:41:06") }
fun autoGenerated_1779007267_line3() { println("Line 3 at 2026-05-17 11:41:06") }
fun autoGenerated_1779007267_line4() { println("Line 4 at 2026-05-17 11:41:06") }
fun autoGenerated_1779007267_line5() { println("Line 5 at 2026-05-17 11:41:06") }

// Auto commit batch 1779007272
fun autoGenerated_1779007272_line1() { println("Line 1 at 2026-05-17 11:41:11") }
fun autoGenerated_1779007272_line2() { println("Line 2 at 2026-05-17 11:41:11") }
fun autoGenerated_1779007272_line3() { println("Line 3 at 2026-05-17 11:41:11") }
fun autoGenerated_1779007272_line4() { println("Line 4 at 2026-05-17 11:41:11") }
fun autoGenerated_1779007272_line5() { println("Line 5 at 2026-05-17 11:41:11") }

// Auto commit batch 1779007276
fun autoGenerated_1779007276_line1() { println("Line 1 at 2026-05-17 11:41:16") }
fun autoGenerated_1779007276_line2() { println("Line 2 at 2026-05-17 11:41:16") }
fun autoGenerated_1779007276_line3() { println("Line 3 at 2026-05-17 11:41:16") }
fun autoGenerated_1779007276_line4() { println("Line 4 at 2026-05-17 11:41:16") }
fun autoGenerated_1779007276_line5() { println("Line 5 at 2026-05-17 11:41:16") }

// Auto commit batch 1779007280
fun autoGenerated_1779007280_line1() { println("Line 1 at 2026-05-17 11:41:19") }
fun autoGenerated_1779007280_line2() { println("Line 2 at 2026-05-17 11:41:19") }
fun autoGenerated_1779007280_line3() { println("Line 3 at 2026-05-17 11:41:19") }
fun autoGenerated_1779007280_line4() { println("Line 4 at 2026-05-17 11:41:19") }
fun autoGenerated_1779007280_line5() { println("Line 5 at 2026-05-17 11:41:19") }

// Auto commit batch 1779007284
fun autoGenerated_1779007284_line1() { println("Line 1 at 2026-05-17 11:41:24") }
fun autoGenerated_1779007284_line2() { println("Line 2 at 2026-05-17 11:41:24") }
fun autoGenerated_1779007284_line3() { println("Line 3 at 2026-05-17 11:41:24") }
fun autoGenerated_1779007284_line4() { println("Line 4 at 2026-05-17 11:41:24") }
fun autoGenerated_1779007284_line5() { println("Line 5 at 2026-05-17 11:41:24") }

// Auto commit batch 1779007288
fun autoGenerated_1779007288_line1() { println("Line 1 at 2026-05-17 11:41:28") }
fun autoGenerated_1779007288_line2() { println("Line 2 at 2026-05-17 11:41:28") }
fun autoGenerated_1779007288_line3() { println("Line 3 at 2026-05-17 11:41:28") }
fun autoGenerated_1779007288_line4() { println("Line 4 at 2026-05-17 11:41:28") }
fun autoGenerated_1779007288_line5() { println("Line 5 at 2026-05-17 11:41:28") }

// Auto commit batch 1779007292
fun autoGenerated_1779007292_line1() { println("Line 1 at 2026-05-17 11:41:31") }
fun autoGenerated_1779007292_line2() { println("Line 2 at 2026-05-17 11:41:31") }
fun autoGenerated_1779007292_line3() { println("Line 3 at 2026-05-17 11:41:31") }
fun autoGenerated_1779007292_line4() { println("Line 4 at 2026-05-17 11:41:31") }
fun autoGenerated_1779007292_line5() { println("Line 5 at 2026-05-17 11:41:31") }

// Auto commit batch 1779007296
fun autoGenerated_1779007296_line1() { println("Line 1 at 2026-05-17 11:41:36") }
fun autoGenerated_1779007296_line2() { println("Line 2 at 2026-05-17 11:41:36") }
fun autoGenerated_1779007296_line3() { println("Line 3 at 2026-05-17 11:41:36") }
fun autoGenerated_1779007296_line4() { println("Line 4 at 2026-05-17 11:41:36") }
fun autoGenerated_1779007296_line5() { println("Line 5 at 2026-05-17 11:41:36") }

// Auto commit batch 1779007300
fun autoGenerated_1779007300_line1() { println("Line 1 at 2026-05-17 11:41:39") }
fun autoGenerated_1779007300_line2() { println("Line 2 at 2026-05-17 11:41:39") }
fun autoGenerated_1779007300_line3() { println("Line 3 at 2026-05-17 11:41:39") }
fun autoGenerated_1779007300_line4() { println("Line 4 at 2026-05-17 11:41:39") }
fun autoGenerated_1779007300_line5() { println("Line 5 at 2026-05-17 11:41:39") }

// Auto commit batch 1779007304
fun autoGenerated_1779007304_line1() { println("Line 1 at 2026-05-17 11:41:43") }
fun autoGenerated_1779007304_line2() { println("Line 2 at 2026-05-17 11:41:43") }
fun autoGenerated_1779007304_line3() { println("Line 3 at 2026-05-17 11:41:43") }
fun autoGenerated_1779007304_line4() { println("Line 4 at 2026-05-17 11:41:43") }
fun autoGenerated_1779007304_line5() { println("Line 5 at 2026-05-17 11:41:43") }

// Auto commit batch 1779007308
fun autoGenerated_1779007308_line1() { println("Line 1 at 2026-05-17 11:41:47") }
fun autoGenerated_1779007308_line2() { println("Line 2 at 2026-05-17 11:41:47") }
fun autoGenerated_1779007308_line3() { println("Line 3 at 2026-05-17 11:41:47") }
fun autoGenerated_1779007308_line4() { println("Line 4 at 2026-05-17 11:41:47") }
fun autoGenerated_1779007308_line5() { println("Line 5 at 2026-05-17 11:41:47") }

// Auto commit batch 1779007312
fun autoGenerated_1779007312_line1() { println("Line 1 at 2026-05-17 11:41:51") }
fun autoGenerated_1779007312_line2() { println("Line 2 at 2026-05-17 11:41:51") }
fun autoGenerated_1779007312_line3() { println("Line 3 at 2026-05-17 11:41:51") }
fun autoGenerated_1779007312_line4() { println("Line 4 at 2026-05-17 11:41:51") }
fun autoGenerated_1779007312_line5() { println("Line 5 at 2026-05-17 11:41:51") }

// Auto commit batch 1779007316
fun autoGenerated_1779007316_line1() { println("Line 1 at 2026-05-17 11:41:55") }
fun autoGenerated_1779007316_line2() { println("Line 2 at 2026-05-17 11:41:55") }
fun autoGenerated_1779007316_line3() { println("Line 3 at 2026-05-17 11:41:55") }
fun autoGenerated_1779007316_line4() { println("Line 4 at 2026-05-17 11:41:55") }
fun autoGenerated_1779007316_line5() { println("Line 5 at 2026-05-17 11:41:55") }

// Auto commit batch 1779007320
fun autoGenerated_1779007320_line1() { println("Line 1 at 2026-05-17 11:41:59") }
fun autoGenerated_1779007320_line2() { println("Line 2 at 2026-05-17 11:41:59") }
fun autoGenerated_1779007320_line3() { println("Line 3 at 2026-05-17 11:41:59") }
fun autoGenerated_1779007320_line4() { println("Line 4 at 2026-05-17 11:41:59") }
fun autoGenerated_1779007320_line5() { println("Line 5 at 2026-05-17 11:41:59") }

// Auto commit batch 1779007324
fun autoGenerated_1779007324_line1() { println("Line 1 at 2026-05-17 11:42:03") }
fun autoGenerated_1779007324_line2() { println("Line 2 at 2026-05-17 11:42:03") }
fun autoGenerated_1779007324_line3() { println("Line 3 at 2026-05-17 11:42:03") }
fun autoGenerated_1779007324_line4() { println("Line 4 at 2026-05-17 11:42:03") }
fun autoGenerated_1779007324_line5() { println("Line 5 at 2026-05-17 11:42:03") }

// Auto commit batch 1779007328
fun autoGenerated_1779007328_line1() { println("Line 1 at 2026-05-17 11:42:07") }
fun autoGenerated_1779007328_line2() { println("Line 2 at 2026-05-17 11:42:07") }
fun autoGenerated_1779007328_line3() { println("Line 3 at 2026-05-17 11:42:07") }
fun autoGenerated_1779007328_line4() { println("Line 4 at 2026-05-17 11:42:07") }
fun autoGenerated_1779007328_line5() { println("Line 5 at 2026-05-17 11:42:07") }

// Auto commit batch 1779007332
fun autoGenerated_1779007332_line1() { println("Line 1 at 2026-05-17 11:42:11") }
fun autoGenerated_1779007332_line2() { println("Line 2 at 2026-05-17 11:42:11") }
fun autoGenerated_1779007332_line3() { println("Line 3 at 2026-05-17 11:42:11") }
fun autoGenerated_1779007332_line4() { println("Line 4 at 2026-05-17 11:42:11") }
fun autoGenerated_1779007332_line5() { println("Line 5 at 2026-05-17 11:42:11") }

// Auto commit batch 1779007336
fun autoGenerated_1779007336_line1() { println("Line 1 at 2026-05-17 11:42:15") }
fun autoGenerated_1779007336_line2() { println("Line 2 at 2026-05-17 11:42:15") }
fun autoGenerated_1779007336_line3() { println("Line 3 at 2026-05-17 11:42:15") }
fun autoGenerated_1779007336_line4() { println("Line 4 at 2026-05-17 11:42:15") }
fun autoGenerated_1779007336_line5() { println("Line 5 at 2026-05-17 11:42:15") }

// Auto commit batch 1779007340
fun autoGenerated_1779007340_line1() { println("Line 1 at 2026-05-17 11:42:19") }
fun autoGenerated_1779007340_line2() { println("Line 2 at 2026-05-17 11:42:19") }
fun autoGenerated_1779007340_line3() { println("Line 3 at 2026-05-17 11:42:19") }
fun autoGenerated_1779007340_line4() { println("Line 4 at 2026-05-17 11:42:19") }
fun autoGenerated_1779007340_line5() { println("Line 5 at 2026-05-17 11:42:19") }

// Auto commit batch 1779007344
fun autoGenerated_1779007344_line1() { println("Line 1 at 2026-05-17 11:42:23") }
fun autoGenerated_1779007344_line2() { println("Line 2 at 2026-05-17 11:42:23") }
fun autoGenerated_1779007344_line3() { println("Line 3 at 2026-05-17 11:42:23") }
fun autoGenerated_1779007344_line4() { println("Line 4 at 2026-05-17 11:42:23") }
fun autoGenerated_1779007344_line5() { println("Line 5 at 2026-05-17 11:42:23") }

// Auto commit batch 1779007348
fun autoGenerated_1779007348_line1() { println("Line 1 at 2026-05-17 11:42:27") }
fun autoGenerated_1779007348_line2() { println("Line 2 at 2026-05-17 11:42:27") }
fun autoGenerated_1779007348_line3() { println("Line 3 at 2026-05-17 11:42:27") }
fun autoGenerated_1779007348_line4() { println("Line 4 at 2026-05-17 11:42:27") }
fun autoGenerated_1779007348_line5() { println("Line 5 at 2026-05-17 11:42:27") }

// Auto commit batch 1779007352
fun autoGenerated_1779007352_line1() { println("Line 1 at 2026-05-17 11:42:31") }
fun autoGenerated_1779007352_line2() { println("Line 2 at 2026-05-17 11:42:31") }
fun autoGenerated_1779007352_line3() { println("Line 3 at 2026-05-17 11:42:31") }
fun autoGenerated_1779007352_line4() { println("Line 4 at 2026-05-17 11:42:31") }
fun autoGenerated_1779007352_line5() { println("Line 5 at 2026-05-17 11:42:31") }

// Auto commit batch 1779007356
fun autoGenerated_1779007356_line1() { println("Line 1 at 2026-05-17 11:42:35") }
fun autoGenerated_1779007356_line2() { println("Line 2 at 2026-05-17 11:42:35") }
fun autoGenerated_1779007356_line3() { println("Line 3 at 2026-05-17 11:42:35") }
fun autoGenerated_1779007356_line4() { println("Line 4 at 2026-05-17 11:42:35") }
fun autoGenerated_1779007356_line5() { println("Line 5 at 2026-05-17 11:42:35") }

// Auto commit batch 1779007360
fun autoGenerated_1779007360_line1() { println("Line 1 at 2026-05-17 11:42:39") }
fun autoGenerated_1779007360_line2() { println("Line 2 at 2026-05-17 11:42:39") }
fun autoGenerated_1779007360_line3() { println("Line 3 at 2026-05-17 11:42:39") }
fun autoGenerated_1779007360_line4() { println("Line 4 at 2026-05-17 11:42:39") }
fun autoGenerated_1779007360_line5() { println("Line 5 at 2026-05-17 11:42:39") }

// Auto commit batch 1779007364
fun autoGenerated_1779007364_line1() { println("Line 1 at 2026-05-17 11:42:43") }
fun autoGenerated_1779007364_line2() { println("Line 2 at 2026-05-17 11:42:43") }
fun autoGenerated_1779007364_line3() { println("Line 3 at 2026-05-17 11:42:43") }
fun autoGenerated_1779007364_line4() { println("Line 4 at 2026-05-17 11:42:43") }
fun autoGenerated_1779007364_line5() { println("Line 5 at 2026-05-17 11:42:43") }

// Auto commit batch 1779007368
fun autoGenerated_1779007368_line1() { println("Line 1 at 2026-05-17 11:42:47") }
fun autoGenerated_1779007368_line2() { println("Line 2 at 2026-05-17 11:42:47") }
fun autoGenerated_1779007368_line3() { println("Line 3 at 2026-05-17 11:42:47") }
fun autoGenerated_1779007368_line4() { println("Line 4 at 2026-05-17 11:42:47") }
fun autoGenerated_1779007368_line5() { println("Line 5 at 2026-05-17 11:42:47") }

// Auto commit batch 1779007372
fun autoGenerated_1779007372_line1() { println("Line 1 at 2026-05-17 11:42:51") }
fun autoGenerated_1779007372_line2() { println("Line 2 at 2026-05-17 11:42:51") }
fun autoGenerated_1779007372_line3() { println("Line 3 at 2026-05-17 11:42:51") }
fun autoGenerated_1779007372_line4() { println("Line 4 at 2026-05-17 11:42:51") }
fun autoGenerated_1779007372_line5() { println("Line 5 at 2026-05-17 11:42:51") }

// Auto commit batch 1779007376
fun autoGenerated_1779007376_line1() { println("Line 1 at 2026-05-17 11:42:55") }
fun autoGenerated_1779007376_line2() { println("Line 2 at 2026-05-17 11:42:55") }
fun autoGenerated_1779007376_line3() { println("Line 3 at 2026-05-17 11:42:55") }
fun autoGenerated_1779007376_line4() { println("Line 4 at 2026-05-17 11:42:55") }
fun autoGenerated_1779007376_line5() { println("Line 5 at 2026-05-17 11:42:55") }

// Auto commit batch 1779007380
fun autoGenerated_1779007380_line1() { println("Line 1 at 2026-05-17 11:42:59") }
fun autoGenerated_1779007380_line2() { println("Line 2 at 2026-05-17 11:42:59") }
fun autoGenerated_1779007380_line3() { println("Line 3 at 2026-05-17 11:42:59") }
fun autoGenerated_1779007380_line4() { println("Line 4 at 2026-05-17 11:42:59") }
fun autoGenerated_1779007380_line5() { println("Line 5 at 2026-05-17 11:42:59") }
